name: text-editor
services:
- name: web
  github:
    repo: ahappyphrog/text-editor
    branch: main
  build_command: npm run build
  run_command: npx serve -s dist
  http_port: 3000
  routes:
  - path: /
  env:
  - key: NODE_ENV
    value: production n